# react-dockerizing/nginx/nginx.conf
events {}

http {
    include mime.types;
    default_type application/octet-stream;

    server {
        listen 8080;
        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
        }
    }
}