# name: 'CI/CD Workflow'

# on:
#   push:
#     branches:
#       - main # CI 작업을 수행할 브랜치 지정

# jobs:
#   lint:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-node@v4
#         with:
#           node-version: 20
#       - name: Install dependencies
#         run: npm install

#       # - name: Lint check
#       #   run: npm run lint:eslint

#       - name: StyleLint check
#         run: npm run lint:styled

#       - name: Prettier write
#         run: npm run prettier:write

#   cypress-run:
#     runs-on: ubuntu-latest
#     needs: lint
#     strategy:
#       fail-fast: false
#       matrix:
#         containers: [1, 2]
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Install dependencies
#         run: npm install

#       - name: Cypress run
#         uses: cypress-io/github-action@v6
#         with:
#           start: npm run dev
#           wait-on: 'http://localhost:8080'
#           record: true
#           parallel: true
#         env:
#           CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#   accessibility-test:
#     timeout-minutes: 60
#     needs: cypress-run
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-node@v4
#         with:
#           node-version-file: '.nvmrc'

#       - name: Install dependencies
#         run: yarn

#       - name: Install Playwright
#         run: npx playwright install --with-deps

#       - name: Build Storybook
#         run: yarn build-storybook --quiet

#       - name: Serve Storybook and run tests
#         run: |
#           npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
#             "npx http-server storybook-static --port 6006 --silent" \
#             "npx wait-on tcp:6006 && yarn test-storybook"

#   chromatic:
#     runs-on: ubuntu-latest
#     needs: accessibility-test
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0
#       - uses: actions/setup-node@v4
#         with:
#           node-version: 20

#       - name: Install dependencies
#         run: npm install

#       - name: Run Chromatic
#         uses: chromaui/action@latest
#         with:
#           projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

#   deploy-netlify:
#     runs-on: ubuntu-latest
#     needs: chromatic
#     steps:
#       - uses: actions/checkout@v4
#       - name: Deploy to Netlify
#         uses: nwtgck/actions-netlify@v3.0
#         with:
#           publish-dir: './dist'
#           production-branch: main
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           deploy-message: 'Deploy from GitHub Actions'
#           enable-pull-request-comment: false
#           enable-commit-comment: true
#           overwrites-pull-request-comment: true
#         env:
#           NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
#           NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
#         timeout-minutes: 1
